from __future__ import annotations

from app.rag.schemas import RetrievalQuery, RetrievalTrace, RetrievedChunk


def build_trace(
    *,
    req: RetrievalQuery,
    queries: list[str],
    retrieved_chunk_ids: list[str],
    final_chunks: list[RetrievedChunk],
    retrieved_titles: list[str],
    scores: list[float],
    collection_name: str | None = None,
    cache_hit: bool = False,
    detected_topic: str | None = None,
    ml_signal_summary: str | None = None,
    integrity_focus: bool = False,
    requested_top_k: int | None = None,
    effective_top_k: int | None = None,
    token_budget: int | None = None,
    applied_filters: dict | None = None,
    final_categories: list[str] | None = None,
    reranking_changed_order: bool = False,
    initial_candidate_count: int = 0,
    confidence_score: float | None = None,
    confidence_label: str | None = None,
    eligibility_summary: dict | None = None,
) -> RetrievalTrace:
    return RetrievalTrace(
        audience=req.audience,
        query=req.query,
        collection_name=collection_name,
        rewritten_queries=queries,
        expanded_queries=queries,
        retrieved_chunk_ids=retrieved_chunk_ids,
        final_chunk_ids=[c.chunk_id for c in final_chunks],
        retrieved_titles=retrieved_titles,
        selected_titles=[c.document_title for c in final_chunks],
        scores=scores,
        cache_hit=cache_hit,
        detected_topic=detected_topic,
        ml_signal_summary=ml_signal_summary,
        integrity_focus=integrity_focus,
        requested_top_k=requested_top_k,
        effective_top_k=effective_top_k,
        token_budget=token_budget,
        applied_filters=applied_filters or {},
        final_categories=final_categories or [],
        reranking_changed_order=reranking_changed_order,
        keywords_used=list(req.keywords or []),
        text_excerpt=req.text_excerpt,
        title_hint=req.title_hint,
        mode=req.mode,
        degraded_input=bool(req.degraded_input),
        initial_candidate_count=initial_candidate_count,
        confidence_score=confidence_score,
        confidence_label=confidence_label,
        eligibility_summary=eligibility_summary or {},
    )
